version: "3"
services:
  ## CONTRACTS + GRAPH  
  synpress:
    container_name: synpress
    command: sleep infinity
    environment:
      DISPLAY: ":14"
      LIBGL_ALWAYS_INDIRECT: 0
    volumes_from:
      - x11-bridge:rw
    depends_on:
      - x11-bridge
    build:
      dockerfile: Dockerfile
      context: ./OpenQ-Synpress
    network_mode: "host"
    volumes:
      - /app/node_modules
      - ./OpenQ-Synpress:/app
    env_file:
      - ./OpenQ-Synpress/.env

  x11-bridge:
    image: jare/x11-bridge

    network_mode: "host"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"

    restart: always

    environment:
      MODE: tcp
      XPRA_HTML: "yes"
      DISPLAY: ":14"
      XPRA_TCP_PORT: "8080"
      XPRA_PASSWORD: MUST_BE_SOMETHING